appointment/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import login
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic.base import RedirectView, TemplateView
from django.contrib.auth.decorators import login_required
from appointment_service.views import AppointmentListView, AppointmentDetailView, NewAppointmentCreate, DateCreate, \
    TimeCreate, submit_form, SubmittedListView, AppointmentsList, AppointmentsDetail, EventDateList, TimeRangeList

urlpatterns = [

    # User Related urls
    url(r'^users/login/$', login, {'authentication_form': AuthenticationForm}, name='login'),
    url(r'^users/logout/$', auth_views.logout, kwargs={'next_page': 'home'},
        name='auth_logout'),
    url(r'^register/complete/$', RedirectView.as_view(pattern_name='home'),
        name='registration_complete'),
    url(r'^users/', include('registration.backends.simple.urls',
        namespace='users')),
    url(r'^users/profile/$', login_required(TemplateView.as_view(
        template_name='registration/profile.html')), name='profile'),

    url(r'^$', AppointmentListView.as_view(), name='home'),

    url(r'^appointment/(?P<pk>\d+)/info/$', AppointmentDetailView.as_view(), name='appointment'),

    url(r'^new_appointment/$', NewAppointmentCreate.as_view(), name='new_appointment'),

    url(r'^new_date/$', DateCreate.as_view(), name='new_date'),

    url(r'^new_time/$', TimeCreate.as_view(), name='new_time'),

    url(r'^submit_form/$', submit_form, name='submit_form'),

    url(r'^submitted_appointments/$', login_required(SubmittedListView.as_view()), name='submitted'),

    # REST API urls
    url(r'^api/appointments/$', AppointmentsList.as_view()),
    url(r'^api/appointments/(?P<pk>[0-9]+)/$', AppointmentsDetail.as_view()),
    url(r'^api/appointments/dates/$', EventDateList.as_view()),
    url(r'^api/appointments/time/$', TimeRangeList.as_view()),


    url(r'^admin/', admin.site.urls),
]

appointment_service/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

# Create your models here.


class Appointments(models.Model):

    class Meta(object):
        verbose_name = "Appointment"
        verbose_name_plural = "Appointments"
        ordering = ['datetime']

    title = models.CharField(
        max_length=256,
        verbose_name="Title"
    )

    description = models.TextField(
        blank=True,
        null=True,
        verbose_name="Description"
    )

    datetime = models.DateTimeField(
        auto_now_add=True
    )

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return "{}".format(self.title)


class EventDate(models.Model):

    class Meta(object):
        verbose_name = "Date of event"
        verbose_name_plural = "Dates of event"

    date = models.DateField()

    appointment = models.ForeignKey(
        Appointments,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return "{}".format(self.date)


class TimeRange(models.Model):

    class Meta(object):
        verbose_name = "Time range "
        verbose_name_plural = "Time ranges"

    start_time = models.TimeField()

    end_time = models.TimeField()

    appointment = models.ForeignKey(
        Appointments,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return "{}-{}".format(self.start_time, self.end_time)


class SubmittedForms(models.Model):

    class Meta(object):
        verbose_name = "Submitted form "
        verbose_name_plural = "Submitted forms"

    date = models.CharField(
        max_length=256,
        verbose_name="Date"
    )

    time_range = models.CharField(
        max_length=256,
        verbose_name="Time range"
    )

    full_name = models.CharField(
        max_length=256,
        verbose_name="Full name"
    )

    email = models.EmailField(
        max_length=254
    )

    def __str__(self):
        return "{}".format(self.full_name)

appointment_service/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django import forms
from django.forms import ModelForm
from .models import Appointments, EventDate, TimeRange, SubmittedForms
from django.core.urlresolvers import reverse
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from rest_framework import generics
from .serializers import AppointmentsSerializer, EventDateSerializer, TimeRangeSerializer

# Create your views here.


class AppointmentListView(ListView):

    model = Appointments

    template_name = 'index.html'


class AppointmentDetailView(DetailView):

    model = Appointments

    template_name = 'appointment.html'


class NewAppointmentForm(ModelForm):
    class Meta:
        model = Appointments
        fields = ['title', 'description']


class NewAppointmentCreate(LoginRequiredMixin, CreateView):
    login_url = 'login'
    redirect_field_name = 'index.html'

    model = Appointments
    form_class = NewAppointmentForm
    template_name = 'new_appointment.html'

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return HttpResponseRedirect('/')


class NewDateForm(ModelForm):
    class Meta:
        model = EventDate
        fields = ['date']
    appointment = forms.ModelChoiceField(queryset=Appointments.objects.all())

    def save(self, commit=True):
        instance = super().save(commit=False)
        appointment = self.cleaned_data['appointment']
        instance.appointment = Appointments.objects.get(pk=appointment.id)
        instance.save(commit)
        return instance


class NewTimeForm(ModelForm):
    class Meta:
        model = TimeRange
        fields = ['start_time', 'end_time']
    appointment = forms.ModelChoiceField(queryset=Appointments.objects.all())

    def save(self, commit=True):
        instance = super().save(commit=False)
        appointment = self.cleaned_data['appointment']
        instance.appointment = Appointments.objects.get(pk=appointment.id)
        instance.save(commit)
        return instance


class DateCreate(CreateView):

    model = EventDate
    form_class = NewDateForm
    template_name = 'new_date.html'

    def get_success_url(self):
            return reverse('home')


class TimeCreate(CreateView):

    model = TimeRange
    form_class = NewTimeForm
    template_name = 'new_time.html'

    def get_success_url(self):
            return reverse('home')


def submit_form(request):
    if request.method == 'POST':

        data = {'date': request.POST.get('date'),
                'time_range': request.POST.get('time_range'),
                'full_name': request.POST.get('full_name'),
                }

        email = request.POST.get('email')

        try:
            validate_email(email)
        except Exception:
            raise ValidationError('Invalid email', code='invalid')
        else:
            data['email'] = email

        form = SubmittedForms(**data)
        form.save()

    return HttpResponseRedirect(reverse('home'))


class SubmittedListView(ListView):

    model = SubmittedForms

    template_name = 'submitted.html'


# REST API
class AppointmentsList(generics.ListCreateAPIView):
    queryset = Appointments.objects.all()
    serializer_class = AppointmentsSerializer


class AppointmentsDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Appointments.objects.all()
    serializer_class = AppointmentsSerializer


class EventDateList(generics.ListCreateAPIView):
    queryset = EventDate.objects.all()
    serializer_class = EventDateSerializer


class TimeRangeList(generics.ListCreateAPIView):
    queryset = TimeRange.objects.all()
    serializer_class = TimeRangeSerializer

templates/appointment.html
{% extends "index.html" %}

{% block meta_title %}Appointment info{% endblock meta_title %}

{% block content %}

    <h4>{{ appointments.title }}</h4>

    <form method="post" action="{% url "submit_form" %}">

    {% csrf_token %}

    <div class="form-group">


    <label for="date">Choose date:</label><br>

            {% for date in appointments.eventdate_set.all %}

                <input type="radio" name="date" value="{{ date }}"> {{ date }}<br>

            {% endfor %}

    </div>

    <div class="form-group">

    <label for="time">Choose time:</label><br>

            {% for time in appointments.timerange_set.all %}

                <input type="radio" name="time_range" value="{{ time.start_time }} - {{ time.end_time }}">
                {{ time.start_time }} - {{ time.end_time }}<br>

            {% endfor %}

    </div>

    <div class="form-group">
    <label for="full_name">Full name</label>
    <input type="text" class="form-control" id="full_name" value=""
           name="full_name" />
    </div>

    <div class="form-group">
    <label for="email">Email</label>
    <input type="text" class="form-control" id="email" value=""
           name="email" />
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>

    </form>

{% endblock content %}

templates/index.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Appointment service - {% block meta_title %}{% endblock meta_title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap.min.css">
    <link rel="stylesheet" href={{ PORTAL_URL }}{% static "main.css" %}>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-default">
            <h4 class="navbar-text">APPOINTMENT SERVICE</h4>
            <ul class="nav navbar-nav">
                <li><a href="{% url "new_appointment" %}">Create new appointment</a></li>
                <li><a href="{% url "submitted" %}">Submitted</a></li>
            </ul>
            <ul class="nav navbar-nav pull-right">
                {% if user.is_authenticated %}
                    <li><a href="{% url "profile" %}">{{ user.username }}</a></li>
                    <li><a href="{% url "users:auth_logout" %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url "users:auth_login" %}">Login</a></li>
                    <li><a href="{% url "users:registration_register" %}">Register</a></li>
                {% endif %}
            </ul>
            </ul>
        </nav>
    {% block content %}
      <div>
        <h4>List of appointments</h4>
        <ul>
            {% for appointment in object_list %}
            <li><a href="{% url "appointment" appointment.id %}">{{ appointment.title }}</a></li>
            {% endfor %}
        </ul>
      </div>
    {% endblock content %}
    </div>
</body>
</html>

templates/new_appointment.html
{% extends "index.html" %}

{% block meta_title %}New appointment{% endblock meta_title %}

{% block content %}

    <div style="margin-bottom: 20px">
        <form method="post" action="{% url 'new_appointment' %}">
            {% csrf_token %}
            {{ form.as_p }}
          <input type="submit" value="Submit" class="btn"/>
        </form>
    </div>



    <p><a href="{% url 'new_date' %}"><button type="button">Add date</button></a><br></p>
    <p><a href="{% url 'new_time' %}"><button type="button">Add time range</button></a></p>

{% endblock content %}

templates/new_date.html
{% extends "index.html" %}

{% block meta_title %}New date{% endblock meta_title %}

{% block content %}

    <div style="margin-bottom: 20px">
        <form method="post" action="{% url 'new_date' %}">
            {% csrf_token %}
            {{ form.as_p }}
          <input type="submit" value="Submit" class="btn"/>
        </form>
    </div>

{% endblock content %}

templates/new_time.html
{% extends "index.html" %}

{% block meta_title %}New date{% endblock meta_title %}

{% block content %}

    <div style="margin-bottom: 20px">
        <form method="post" action="{% url 'new_time' %}">
            {% csrf_token %}
            {{ form.as_p }}
          <input type="submit" value="Submit" class="btn"/>
        </form>
    </div>

{% endblock content %}

templates/submitted.html
{% extends "index.html" %}

{% block meta_title %}Appointment info{% endblock meta_title %}

{% block content %}

    <div>
        <h4>List of submitted appointments</h4>

            {% for appointment in object_list %}
            <p>Date: {{ appointment.date }}</p>
            <p>Time range: {{ appointment.time_range }}</p>
            <p>Full name: {{ appointment.full_name }}</p>
            <p>Email: {{ appointment.email }}</p>
            <hr>
            {% endfor %}

    </div>

{% endblock content %}